services:
  mysql:
    image: mysql:latest
    ports:
      - 33062:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: 
      always